site_name: Notes for Computer Network
repo_url: https://github.com/chuan-325/net-21sp
repo_name: chuan-325/net-21sp
nav:
  - Home: index.md
  - Chapter 1 计算机网络概述: chap_01.md
  - Chapter 2 直连网络: chap_02.md
theme:
  name: material
  palette:
    primary: teal
    accent: teal
  language: zh
  features:
    # - toc.integrate
    - search.suggest
    - search.highlight
markdown_extensions:
  - mdx_truly_sane_lists
  - attr_list
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      toc_depth: 3
plugins:
  - search:
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
